:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - mailers
  - low_priority

# Scheduled jobs (optional)
:schedule:
  # Example: cleanup old data every day at 2am
  # cleanup_job:
  #   cron: '0 2 * * *'
  #   class: CleanupJob
